version: "3"
services:
    db:
        image: ealgis/postgis:latest
        volumes:
            - ./:/app
            - data:/data
            - tmp:/tmp
        environment:
            - POSTGRES_DB=ealgis
        ports:
            - "5432:5432"

    dataloader:
        image: ealgis/ingest-base:latest
        volumes:
            - ./:/app
            - data:/data
            - tmp:/tmp
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=datastore
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        depends_on:
            - db

volumes:
        data:
        tmp:
